import type { Metadata } from "next";
import { Geist, Geist_Mono, Gamja_Flower } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";

const gamja_flower = Gamja_Flower({
  weight: "400",
  variable: "--font-gamja-flower",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
  authors: [{ name: "Aya Alaa" }, { name: "Omar Assem" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body
        className={`${gamja_flower.variable} ${geistMono.variable} antialiased bg-black`}    >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
